package:
  name: eigen
  version: 3.3

build:
  number: 0

source:
  fn: eigen3.3.tar.bz2
  url: http://bitbucket.org/eigen/eigen/get/3.3.0.tar.gz


requirements:
  build:
    - cmake
  
about:
  home: http://eigen.tuxfamily.org/
  license: MPL2
