package:
  name: eigen
  version: 3.3

build:
  string: rc1

source:
  fn: 3.3-rc1.tar.bz2
  url: http://bitbucket.org/eigen/eigen/get/3.3-rc1.tar.bz2


requirements:
  build:
    - cmake
  
about:
  home: http://eigen.tuxfamily.org/
  license: MPL2
