package:
    name: simage
    version: 1.7.0

source:
    fn: simage.tar.gz
    url: https://github.com/looooo/pivy/releases/download/v0.6.1-0/simage.tar.gz
    sha256: 4b57ed3c4997fbcc8b13823a60c1115cd97f701ada8afd44241f8512a5a9adc0

    patches:

build:
    number: 0
    skip: true  # [py<35]

    features:
        - vc14  # [win]

    track_features:
        - vc14  # [win]

requirements:
    build:
        - ninja  # [win]
        - vc 14  # [win]
        - toolchain
        - cmake
        - gcc  # [unix]
        - qt 4.8.7
        - libpng
        - jpeg
    run:
        - vc 14  # [win]
        - libpng
        - qt 4.8.7

about:
    home: https://bitbucket.org/Coin3D/simage
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING
    summary: Simage, image-library needed by Cin3d.
    description: This is ``simage'', a library with image format loaders and front-ends
                 to common import libraries. simage is meant for use with applications
                 which reads image files as textures.
    doc_url: https://bitbucket.org/Coin3D/simage
    dev_url: https://bitbucket.org/Coin3D/simage

extra:
    recipe-maintainers:
        - looooo
