package:
  name: shiboken
  version: 1.2.4

source:
  git_url: https://github.com/PySide/Shiboken

requirements:
  build:
    - cmake
    - qt
    - python
  run:
    - qt
    - python

build:
  number: 1

#test:
#  commands:
#    - shiboken --help
#  imports:
#    - shiboken

about:
    home: https://github.com/PySide/Shiboken
    license: LGPL