package:
  name: shiboken
  version: 1.2.4

source:
  git_url: https://github.com/PySide/Shiboken
  git_tag: master

  patches:


requirements:
  build:
    - cmake
    - qt >=4
    - python
  run:
    - qt
    - python

build:
  number: 1

test:
 commands:
   - shiboken --help
 imports:
   - shiboken

about:
    home: https://github.com/PySide/Shiboken
    license: LGPL
