package:
  name: shiboken
  version: 1.2.4

source:
  fn: shiboken.tar.gz
  url: https://github.com/pyside/Shiboken/archive/1.2.4.tar.gz
  
  patches:
    - cmake.patch

requirements:
  build:
    - cmake
    - qt
    - python
  run:
    - qt
    - python

build:
  number: 3

#test:
#  commands:
#    - shiboken --help
#  imports:
#    - shiboken

about:
    home: https://github.com/PySide/Shiboken
    license: LGPL
