package:
    name: libmed
    version: 3.1.0

build:
    number: 2
    features:
        - vc14    # [win and py>=35]
    detect_binary_files_with_prefix: True

source:
    git_url: https://github.com/vejmarie/libMED.git
    git_tag: master

    patches:
        - comment.patch

requirements:
    build:
        - toolchain
        - ninja  # [win]
        - python # [win]
        - vc 14  # [win and py>=35]
        - cmake >=3.1
        - hdf5 1.8.17.*

about:
    summary: libmed
