package:
    name: libmed
    version: 3.1.0

build:
    number: 2

source:
    git_url: https://github.com/vejmarie/libMED.git
    git_tag: master

    track_features:
         - vc14                                # [win and py35]

requirements:
    build:
        - ninja  # [win]
        - cmake
        - hdf5 1.8.17.*

about:
    summary: libmed
