package:
    name: libmed
    version: 3.1.0

source:
    git_url: https://github.com/vejmarie/libMED.git
    git_tag: master

    patches:
        - comment.patch

build:
    number: 4
    features:
        - vc14  # [win and py>=35]

requirements:
    build:
        - toolchain
        - gcc  # [unix]
        - vc 14   # [win and py>=35]
        - ninja  # [win]
        - cmake
        - hdf5 1.8.18.*
        - zlib 1.2*
    run:
        - libgcc  # [unix]
        - vc 14  # [win and py>=35]
        - hdf5 1.8.18.*
        - zlib 1.2*

about:
    summary: libmed
