{%set name = "pyrate"%}
{%set version = "0.2.0.master"%}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/mess42/pyrate
  git_tag: master
  patches:
    - setup.patch

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - pip
    - python
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - sympy
    - ruamel.yaml

test:
  imports:
    - pyrateoptics

about:
  license: GPL2
  license_family: GPL
  license_file: LICENSE.txt
  summary: Pyrate - Optical Raytracing with Python
