# This file created by conda-build 3.0.21+2.gd8f972ad5
# meta.yaml template originally from:
# C:\Users\builder\conda\aggregate\console_shortcut-feedstock\recipe, last modified Tue Sep 12 10:14:18 2017
# ------------------------------------------------

package:
    name: freecad-launcher
    version: 0.0.0

build:
    number: '0'

requirements:
    run:
        - python
        - menuinst

about:
    license: BSD
    summary: FreeCAD launcher

extra:
    copy_test_source_files: true
    final: true
