package:
    name: xfoil
    version: 6.97

source:
    git_url: https://github.com/RobotLocomotion/xfoil
    git_tag: master

build:
    number: 0

requirements:
    build:
        - cmake
        - gcc
    run:
        
about:
    home: http://web.mit.edu/drela/Public/web/xfoil/
    license: GPL 2
    license_family: GPL
    # license_file: COPYING
    summary: subsonic airfoil development system
    description: XFOIL is an interactive program for the design and analysis of subsonic isolated airfoils. 
    doc_url: http://web.mit.edu/drela/Public/web/xfoil/
    dev_url: https://github.com/RobotLocomotion/xfoil/blob/master/CMakeLists.txt

extra:
    recipe-maintainers:
        - looooo
