package:
    name: freecad
    version: 0.17

build:
    number: 5

    features:
        - vc14  # [win and py>=35]
        - occt7.1.0

    track_features:
        - vc14  # [win and py>=35]
        - occt7.1.0

source:
    git_url: https://github.com/looooo/FreeCAD
    git_tag: py3-27

    patches:
        #

requirements:
    build:
        - vc 14  # [win and py>=35]
        - ninja  # [win and py>=35]
        - cmake
        - swig
        - eigen
        - boost 1.63.*
        - python
        - matplotlib
        - coin3d
        - pivy
        - qt 4.8.7
        - pyside
        - occt 7.1.0
        - netgen
        - vtk 7.1.0
        - libmed
        - hdf5
        - xerces-c
        - zlib 1.2.*
    run:
        - vc 14  # [win and py>=35]
        - boost 1.63.*
        - python
        - numpy
        - matplotlib
        - coin3d
        - pivy
        - qt 4.8.7
        - pyside
        - occt 7.1.0
        - netgen
        - vtk 7.1.0
        - libmed
        - xerces-c
        - zlib 1.2*
        - git
about:
    summary: freecad

