package:
    name: freecad
    version: 0.17

build:
    number: 9

    features:
        - vc14  # [win and py>=35]
        - occt7.2.0

    track_features:
        - vc14  # [win and py>=35]
        - occt7.2.0

source:
    git_url: https://github.com/FreeCAD/FreeCAD
    git_tag: master

requirements:
    build:
        - nomkl  # [unix]
        - vc 14  # [win and py>=35]
        - ninja  # [win and py>=35]
        - cmake
        - swig
        - eigen
        - boost-cpp 1.65*
        - pybind11  # [unix]
        - boost 1.65*  # [not unix]
        - python
        - matplotlib
        - coin3d
        - pivy
        - qt 5.*
        - pyside2
        - occt
        - netgen
        - vtk
        - libmed
        - hdf5
        - xerces-c
        - zlib 1.2.*
        - doxygen
        - git
    run:
        - vc 14  # [win and py>=35]
        - boost-cpp 1.65*
        - boost 1.65*  # [not unix]
        - python
        - numpy
        - matplotlib
        - coin3d
        - pivy
        - qt 5.*
        - pyside2
        - occt
        - netgen
        - vtk
        - libmed
        - xerces-c
        - zlib 1.2*
        - git
        - calculix  # [unix]
about:
    summary: freecad

