package:
    name: freecad
    version: 0.17

build:
    number: 2

source:
    git_url: https://github.com/looooo/FreeCAD
    git_tag: py3-21

    patches:
        # - none

requirements:
    build:
        - cmake
        - swig
        - eigen
        - hdf5
        - boost-cpp 1.63.0 2
        - python
        - matplotlib
        - coin3d
        - pivy
        - qt 4.8.7 7
        - pyside
        - pyside-tools
        - occt
        - netgen
        - vtk 7.1.0
        - libmed
        - xerces-c
    run:
        - boost-cpp 1.63.0 2
        - python
        - numpy
        - matplotlib
        - coin3d
        - pivy
        - qt 4.8.7 7
        - pyside
        - occt
        - netgen
        - vtk 7.1.0
        - libmed
        - xerces-c
about:
    summary: freecad

