package:
    name: freecad
    version: 0.17

build:
    number: 8

source:
    git_url: https://github.com/looooo/FreeCAD
    git_tag: occ_patch

    # for python 3
    # git_url: https://github.com/looooo/FreeCAD
    # git_tag: master

    patches:
        # - occ_cmake.patch
        # - netgen_1.patch
        # - all.patch1

requirements:
    build:
        - python
        - cmake
        - eigen 3.3
        - swig
        - shiboken
        - pyside
        - pyside-tools
        - coin
        - pivy
        - boost 1.60.0
        - occt
        - qt
        - netgen
        - libmed
        - vtk
        - hdf5
        - xerces-c
        - libuuid
    run:
        - python
        - numpy
        - matplotlib
        - pyside
        - pivy
        - boost 1.60.0
        - coin
        - occt
        - netgen
        - vtk
        - libmed
        - xerces-c
about:
    summary: freecad
