package:
    name: freecad
    version: 0.17

build:
    number: 4

source:
    git_url: https://github.com/looooo/FreeCAD
    git_tag: py3-23

    patches:
        # - none

    features:
        - vc14  # [win]

    track_features:
        - vc14  # [win and py35]
        - occt7.1.0

requirements:
    build:
        - cmake
        - swig
        - eigen
        - boost-cpp 1.63.*
        - python
        - matplotlib
        - coin3d
        - pivy
        - qt 4.8.7
        - pyside
        - occt
        - netgen
        - vtk 7.1.0
        - libmed
        - xerces-c
    run:
        - boost-cpp 1.63.*
        - python
        - numpy
        - matplotlib
        - coin3d
        - pivy
        - qt 4.8.7
        - pyside
        - occt
        - netgen
        - vtk 7.1.0
        - libmed
        - xerces-c
about:
    summary: freecad

