package:
    name: freecad
    version: 0.17

build:
    number: 6

source:
    git_url: https://github.com/FreeCAD/FreeCAD
    git_tag: master

    # for python 3
    # git_url: https://github.com/looooo/FreeCAD
    # git_tag: master

    patches:
        # - occ_cmake.patch
        # - netgen_1.patch
        - all.patch

requirements:
    build:
        - python
        - matplotlib
        - cmake
        - eigen 3.3
        - swig
        - shiboken
        - pyside
        - pyside-tools
        - coin
        - pivy
        - boost 1.60.0
        - occt
        - qt
        - netgen
        - libmed
        - hdf5
        - xerces-c
    run:
        - python
        - numpy
        - matplotlib
        - pyside
        - pivy
        - boost 1.60.0
        - coin
        - occt
        - netgen
        - vtk
        - libmed
about:
    summary: freecad
