package:
    name: freecad
    version: 0.17

build:
    number: 5

    features:
        - vc14  # [win and py>=35]
        - occt7.1.0

    track_features:
        - vc14  # [win and py>=35]
        - occt7.1.0

source:
    git_url: https://github.com/looooo/FreeCAD
    git_tag: master

requirements:
    build:
        - nomkl  # [unix]
        - vc 14  # [win and py>=35]
        - ninja  # [win and py>=35]
        - cmake
        - swig
        - eigen
        - boost
        - boost-cpp
        - python
        - matplotlib
        - coin3d
        - pivy
        - qt 4.*
        - pyside
        - occt
        - netgen
        - vtk
        - libmed
        - hdf5
        - xerces-c
        - zlib 1.2.*
    run:
        - vc 14  # [win and py>=35]
        - boost
        - boost-cpp
        - python
        - numpy
        - matplotlib
        - coin3d
        - pivy
        - qt 4.*
        - pyside
        - occt
        - netgen
        - vtk
        - libmed
        - xerces-c
        - zlib 1.2*
        - git
about:
    summary: freecad

