package:
    name: freecad
    version: 0.17

build:
    number: 6

    features:
        - vc14  # [win and py>=35]
        - occt7.2.0

    track_features:
        - vc14  # [win and py>=35]
        - occt7.2.0

source:
    fn: FreeCAD.tar.gz
    url: https://github.com/FreeCAD/FreeCAD/archive/master.tar.gz
    patches:
        - qt5.patch

requirements:
    build:
        - nomkl  # [unix]
        - vc 14  # [win and py>=35]
        - ninja  # [win and py>=35]
        - cmake
        - swig
        - eigen
        - boost-cpp 1.64*
        - pybind11 2.1.*  # [unix]
        - boost 1.64*  # [not unix]
        - python
        - matplotlib
        - coin3d
        - pivy
        - qt 5.*
        - pyside2
        - occt
        - netgen
        - vtk
        - libmed
        - hdf5
        - xerces-c
        - zlib 1.2.*
        - doxygen
        - git
    run:
        - vc 14  # [win and py>=35]
        - boost-cpp 1.64*
        - boost 1.64*  # [not unix]
        - python
        - numpy
        - matplotlib
        - coin3d
        - pivy
        - qt 5.*
        - pyside2
        - occt
        - netgen
        - vtk
        - libmed
        - xerces-c
        - zlib 1.2*
        - git
about:
    summary: freecad

