package:
    name: freecad_py3
    version: 0.17

build:
    number: 0

source:
    git_url: https://github.com/looooo/FreeCAD
    git_tag: netgen6.1_interface

    # for python 3
    # git_url: https://github.com/looooo/FreeCAD
    # git_tag: master

    patches:
        # - occ_cmake.patch
        # - netgen_1.patch
        # - all.patch1

requirements:
    build:
        - python
        - cmake
        - eigen 3.3
        - swig
        - shiboken
        - pyside
        - pyside-tools
        - coin
        - pivy
        - boost
        - occt
        - qt 4.8.7 0
        - netgen
        - libmed
        - vtk 7.0.0
        - hdf5
        - xerces-c
    run:
        - python
        - numpy
        - matplotlib
        - pyside
        - pivy
        - boost
        - coin
        - occt
        - netgen
        - vtk 7.0.0
        - libmed
        - xerces-c
        - qt 4.8.7 0
about:
    summary: freecad
