package:
  name: pyside
  version: 1.2.4

source:
  git_url: https://github.com/PySide/PySide

build:
  number: 2

requirements:
  build:
    - cmake     [unix]
    - qt        [unix]
    - libpng    [linux]
    - shiboken  [unix]
    - python
  run:
    - qt        [unix]
    - shiboken  [unix]
    - libpng    [linux]
    - python
    - python.app  [osx]

about:
  home: https://pypi.python.org/pypi/PySide
  license: LGPL
