package:
    name: calculix
    version: 2.12

source:
    git_url: https://github.com/easyw/ccx_prool
    git_tag: master

    patches:

build:
    number: 0
    skip: true  # [py<35]

    features:
        - vc14  # [win]

    track_features:
        - vc14  # [win]

requirements:
    build:
        - vc 14  # [win]
        - toolchain
        - perl
    run:
        - vc 14  # [win]

about:
    home: http://www.dhondt.de/
    license: GPL 2
    license_family: GPL
    # license_file: COPYING
    summary: 3D Structural Finite Element Program
    description: A Free Software Three-Dimensional Structural 
                 Finite Element Program
    doc_url: http://www.dhondt.de/ccx_2.12.pdf
    dev_url: http://www.dhondt.de/

extra:
    recipe-maintainers:
        - looooo
