package:
  name: libarea
  version: 0.0.1

build:
  number: 0

source:
  git_url: https://github.com/looooo/libarea

requirements:
  build:
    - ninja  # [win]
    - vc 14  # [win and py>=35]
    - python
    - cmake
    - pybind11
  run:
    - vc 14  # [win and py>=35]
    - python

about:
  summary: area library