package:
    name: smesh
    version: 6.7.5

source:
    git_url: https://github.com/LaughlinResearch/SMESH
    git_tag: master

build:
    number: 0

requirements:
    build:
        - toolchain
        - cmake
        - ninja  # [win]
        - vc 14  # [win]
        - gcc  # [unix]
        - boost-cpp
        - occt 7.2.0
        - netgen
        - vtk 8.*

    run:
        - libgcc  # [unix]
        - vc 14  # [win]
        - boost-cpp
        - occt 7.2.0
        - netgen
        - vtk 8.*

about:
    home: https://github.com/tpaviot/smesh
    license: LGPL
    summary: A complete MESH framework based on the OCE library.
