{% set name = "smesh" %}
{% set version = "8.3.0" %}
{% set sha256 = "" %}

package:
    name: {{ name }}
    version: {{ version }}

# source:
#     git_url: https://github.com/looooo/SMESH
#     git_tag: master

build:
    number: 3
    features:
        - vc14  # [win and py36]
    track_features:
        - vc14  # [win and py36]

requirements:
    build:
        - toolchain
        - cmake
        - ninja
        - vc 14  # [win]
        - boost-cpp 1.66*
        - occt 7.2.0
        - netgen
        - vtk 8.*
        - libmed
        - pthread-stubs  # [unix]
        - pthreads-win32  # [win]

    run:
        - vc 14  # [win]
        - boost-cpp 1.66*
        - occt 7.2.0
        - netgen
        - vtk 8.*
        - libmed
        - pthread-stubs  # [unix]
        - pthreads-win32  # [win]

about:
    home: https://github.com/LaughlinResearch/SMESH
    license: LGPL
    summary: A complete MESH framework based on the OCCT library.
