package:
    name: smesh
    version: 8.3.0

source:
    git_url: https://github.com/LaughlinResearch/SMESH
    git_tag: med_support

build:
    number: 0
    features:
        - vc14  # [win and py36]
    track_features:
        - vc14  # [win and py36]

requirements:
    build:
        - toolchain
        - cmake
        - ninja  # [win]
        - vc 14  # [win]
        - gcc  # [unix]
        - boost-cpp
        - occt 7.2.0
        - netgen
        - vtk 8.*
        - libmed
        -  pthread-stubs

    run:
        - libgcc  # [unix]
        - vc 14  # [win]
        - boost-cpp
        - occt 7.2.0
        - netgen
        - vtk 8.*
        - libmed
        -  pthread-stubs 

about:
    home: https://github.com/LaughlinResearch/SMESH
    license: LGPL
    summary: A complete MESH framework based on the OCCT library.
