package:
    name: pyocct
    version: 7.2.0

source:
    git_url: https://github.com/looooo/pyOCCT
    git_tag: master


build:
    number: 2
    features:
        - vc14  # [win]

requirements:
    build:
        - toolchain
        - vc 14  # [win and py>=35]
        - gcc  # [unix]
        - cmake
        - ninja
        - python
        - pybind11 2.3.0
        - occt 7.2.0
        - smesh
        - vtk
        - netgen
    run:
        - vc 14  # [win and py>=35]
        - libgcc  # [unix]
        - python
        - occt 7.2.0
        - smesh
        - vtk
        - netgen

test:
    imports:
        - OCCT
        - OCCT.Exchange
        - OCCT.Boolean
        - OCCT.SMESH

about:
    summary: python bindings to OCCT
