package:
    name: pyocct
    version: 0.0.1

# source:
    # git_url: https://github.com/LaughlinResearch/pyOCCT
    # git_tag: support_cad_channel


build:
    number: 0
    features:
        - vc14  # [win]

requirements:
    build:
        - toolchain
        - cmake
        - ninja  # [win]
        - vc 14  # [win and py>=35]
        - python
        - pybind11 2.3.0
        - occt 7.2.0
        - smesh
        - vtk
        - netgen
    run:
        - vc 14  # [win and py>=35]
        - python
        - occt 7.2.0
        - smesh
        - vtk
        - netgen

test:
    imports:
        - OCCT

about:
    summary: python bindings to OCCT
