package:
  name: pivy
  version: 0.6.0

build:
  number: 2

source:
  git_url: https://github.com/looooo/pivy
  
requirements:
  build:
    - python
    - swig
    - coin3d
  run:
    - python
    - coin3d

about:
  summary: python buindings to coin
