package:
  name: pivy
  version: 0.6.0

build:
  number: 3

source:
  git_url: https://github.com/looooo/pivy
  
requirements:
  build:
    - cmake    # [win]
    - python
    - swig 3.0.8  # [win]
    - swig        # [unix]
    - coin3d
  run:
    - python
    - coin3d

about:
  summary: python buindings to coin
