package:
    name: pivy
    version: 0.6.0

source:
    git_url: https://github.com/looooo/pivy

build:
    number: 3
    features:
        - vc14  # [win and py>=35]

    track_features:
        - vc14  # [win and py>=35]
  
requirements:
    build:
        - python
        - swig 3.0.8  # [win]
        - swig        # [unix]
        - coin3d
        - vc 14  # [win and py>=35]
    run:
        - python
        - coin3d
        - vc 14  # [win and py>=35]

about:
    summary: python buindings to coin
