package:
    name: pivy
    version: 0.6.2

source:
    git_url: https://github.com/looooo/pivy
    git_tag: master
    # fn: pivy.tar.gz
    # url: https://github.com/looooo/pivy/archive/v0.6.1-0.tar.gz
    # sha256: 9def3f8d19f90fa66e4511da1d301ee921005fb6b0e114a1bb604e4360462f23

build:
    string: py35_dev_2 # [py>=35]
    string: py27_dev_2 # [py<35]
    features:
        - vc14  # [win]

    track_features:
        - vc14  # [win]
  
requirements:
    build:
        - python
        - swig 3.0.8  # [win]
        - swig  # [unix]
        - coin3d
        - vc 14  # [win]
        - colorama
        - soqt #  [linux]
    run:
        - python
        - coin3d
        - soqt  # [linux]
        - vc 14  # [win]

test:
    imports:
        - pivy.coin

about:
    home: https://github.com/looooo/pivy
    license: ISC License
    license_family: BSD
    license_file: LICENSE
    summary: python bindings to coin3d.
    doc_url: https://github.com/looooo/pivy
    dev_url: https://github.com/looooo/pivy

extra:
    recipe-maintainers:
        - looooo
