package:
    name: netgen
    version: 6.2

source:
    git_url: https://github.com/looooo/netgen
    git_tag: 6.2_rebased5

build:
    number: 5
    features:
        - vc14  # [win and py>=35]
        - occt7.2.0

    track_features:
        - vc14  # [win and py>=35]
        - occt7.2.0

requirements:
    build:
        - cmake
        - vc 14  # [win and py>=35]
        - ninja  # [win and py>=35]
        - occt
        - python
        - pybind11
    run:
        - occt
        - vc 14  # [win and py>=35]
        - python

test:
    imports:
        - netgen

about:
    home: https://sourceforge.net/projects/netgen-mesher/
    license: LGPL
    license_family: LGPL
    summary: this is netgen
    description: NETGEN is an automatic 3d tetrahedral mesh generator.
                 It accepts input from constructive solid geometry (CSG) or boundary representation (BRep) from
                 STL file format. The connection to a geometry kernel allows the handling of IGES and STEP files.
                 NETGEN contains modules for mesh optimization and hierarchical mesh refinement.
                 Netgen is open source based on the LGPL license. It is available for Unix/Linux and Windows. 
    doc_url: http://www.hpfem.jku.at/netgen/
    dev_url: https://sourceforge.net/projects/netgen-mesher/