package:
    name: freecad
    version: 0.17

build:
    number: 0

    patches:
        # - none

    track_features:
        - vc14                                # [win and py35]
        - occt7.1.0

requirements:
    build:
        - cmake
        - swig
        - eigen
        - hdf5
        - boost-cpp
        - python
        # - matplotlib ---not yet available
        - coin3d
        - pivy
        - qt 5.6.2
        - pyside2
        - pyside2-tools
        - shiboken2
        - occt
        - netgen
        - vtk 7.1.0
        - libmed
        - xerces-c
    run:
        - boost-cpp
        - python
        - numpy
        - matplotlib
        - coin3d
        - pivy
        - qt 5.6.2
        - pyside2
        - occt
        - netgen
        - vtk 7.1.0
        - libmed
        - xerces-c
about:
    summary: freecad
