package:
  name: netgen
  version: 6.1

build:
  number: 5

source:
  git_url: https://github.com/looooo/netgen
  git_tag: master

requirements:
  build:
    - occt
    - tk 8.6
  run:
    - occt
    - tk 8.6

about:
  summary: netgen
