{% set name = "opencamlib" %}
{% set version = "2018.08" %}
{% set commit = "8e8337f61b05" %}
{% set sha256 = "8319cfa699afac0e5f19054222c25a7ad655f018f7c3c7b53f626e7b167cb08e" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}.tar.gz
    url: https://github.com/aewallin/{{ name }}/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

    # patches:
    #    - boost.patch
    #    - boost_py3.patch  # [py != 27]

build:
    number: 0

requirements:
    build:
        - {{ compiler("cxx") }}
        - ninja  # [win and py>=35]
        - cmake
    host:
        - boost
        - python
        - doxygen
    run:
        - boost
        - python
about:
    home: http://www.anderswallin.net/CAM/
    license: GPL3.0
    license_family: GPL
    summary: OpenCAMLib (ocl)
    description: OpenCAMLib (ocl) is a c++ library for creating toolpaths for cnc-machines
                 such as mills and lathes.
    doc_url: http://www.anderswallin.net/CAM/
    dev_url: https://github.com/aewallin/opencamlib