{% set name = "solvespace" %}
{% set version = "2.3_fc" %}
{% set sha256 = "d2e46e34265fa8f75617f500d25ae8e8bd468967e45fb8fb3e064ee53432911f" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}_{{ version }}.tar.gz
    url: https://github.com/realthunder/{{ name }}/archive/python.tar.gz
    sha256: {{ sha256 }}
    patches:
        - no_gui.patch

build:
    number: 1
    skip: true  # [py<36]

requirements:
    build:
        - {{ compiler("cxx") }}
        - ninja
        - cmake
        - swig
    host:
        - python
        - libpng
        - zlib
        - fontconfig
        - json-c
        - libglu
    run:
        - python
test:
    imports:
        - _slvs
