package:
    name: freecad-debug
    version: 0.17

build:
    number: 6

    features:
        - vc14  # [win and py>=35]
        - occt7.2.0

    track_features:
        - vc14  # [win and py>=35]
        - occt7.2.0

requirements:
    build:
        - nomkl  # [unix]
        - vc 14  # [win and py>=35]
        - ninja  # [win and py>=35]
        - cmake
        - swig
        - eigen
        - boost-cpp
        - pybind11 2.1.*
        - python
        - matplotlib
        - coin3d
        - pivy
        - qt 5.*
        - pyside2
        - occt
        - netgen
        - vtk
        - libmed
        - hdf5
        - xerces-c
        - zlib 1.2.*
        - doxygen
    run:
        - vc 14  # [win and py>=35]
        - boost-cpp
        - python
        - numpy
        - matplotlib
        - coin3d
        - pivy
        - qt 5.*
        - pyside2
        - occt
        - netgen
        - vtk
        - libmed
        - xerces-c
        - zlib 1.2*
        - git
about:
    summary: freecad

