package:
    name: soqt
    version: 1.5.0

# there is a problem with the zipped version of the cmake-soqt branch
# somehow there are some differences between zipped and direct cloned repo.
# I have no idea what exactly is different.
# So building manually is the simplest option:
    # 1: hg clone https://bitbucket.org/roboticslibrary/soqt
    # 2: change in CmakeList.txt coin::coin -> coin 2x
    # 3: select path to soqt dir in the build.sh/build.bat


build:
    number: 0
    skip: true  # [py<35]

    features:
        - vc14  # [win]

    track_features:
        - vc14  # [win]

requirements:
    build:
        - vc 14  # [win]
        - ninja  # [win]
        - cmake
        - qt 4.8.7
        - coin3d
    run:
        - vc 14  # [win]
        - qt 4.8.7
        - coin3d

about:
    home: https://bitbucket.org/Coin3D/soqt
    # license: BSD 3-Clause
    # license_family: BSD
    # license_file: COPYING
    summary: Simage, image-library needed by Cin3d.
    description: SoQt is a Qt GUI component toolkit library for Coin.  It is also compatible
                 with SGI and TGS Open Inventor, and the API is based on the API of the
                 InventorXt GUI component toolkit.
    doc_url: https://bitbucket.org/Coin3D/soqt
    dev_url: https://bitbucket.org/Coin3D/soqt

extra:
    recipe-maintainers:
        - looooo
