package:
    name: soqt
    version: "1.6.0a"

source:
    fn: soqt.tar.gz
    url: https://github.com/FreeCAD/pivy/releases/download/0.6.2/soqt.tar.gz
    sha256: d6e302cbd8b5a9e02bae214c5d4e5016f182f0d17546be0bcd9aed0e02cd3fe6 

build:
    number: 2
    skip: true  # [py<35]

    features:
        - vc14  # [win]

    track_features:
        - vc14  # [win]

requirements:
    build:
        - toolchain
        - vc 14  # [win]
        - ninja  # [win]
        - gcc  # [linux]
        - cmake
        - qt 5.*
        - coin3d
    run:
        - vc 14  # [win]
        - libgcc  # [linux]
        - qt 5.*
        - coin3d

about:
    home: https://bitbucket.org/Coin3D/soqt
    # license: BSD 3-Clause
    # license_family: BSD
    # license_file: COPYING
    summary: SoQt library needed by Coin3d.
    description: SoQt is a Qt GUI component toolkit library for Coin.  It is also compatible
                 with SGI and TGS Open Inventor, and the API is based on the API of the
                 InventorXt GUI component toolkit.
    doc_url: https://bitbucket.org/Coin3D/soqt
    dev_url: https://bitbucket.org/Coin3D/soqt

extra:
    recipe-maintainers:
        - looooo
